@ cdecl spifns_bccmd_cmd(ptr long long)
@ cdecl spifns_bccmd_init(long long)
@ cdecl spifns_getvarlist(ptr ptr)
@ cdecl spifns_init()
@ cdecl spifns_getvar(ptr)
@ cdecl spifns_get_last_error(ptr ptr)
@ cdecl spifns_set_debug_callback(ptr)
@ cdecl spifns_get_version()
@ cdecl spifns_close()
@ cdecl spifns_chip_select(long)
@ cdecl spifns_command(str)
@ cdecl spifns_enumerate_ports(ptr ptr)
@ cdecl spifns_sequence(ptr long)
@ cdecl spifns_bluecore_xap_stopped()
@ cdecl spifns_clear_last_error()
# Below is a part for the stream API
@ cdecl spifns_stream_bccmd_cmd(long ptr long long)
@ cdecl spifns_stream_bccmd_init(long long long)
@ cdecl spifns_count_streams()
@ cdecl spifns_get_last_error32(ptr ptr)
@ cdecl spifns_stream_bluecore_xap_stopped(long)
@ cdecl spifns_stream_chip_select(long long)
@ cdecl spifns_stream_close(long)
@ cdecl spifns_stream_command(long ptr)
@ cdecl spifns_stream_get_device_id(long ptr long)
@ cdecl spifns_stream_getvar(long ptr)
@ cdecl spifns_stream_init(ptr)
@ cdecl spifns_stream_lock(long long)
@ cdecl spifns_stream_sequence(long ptr long)
@ cdecl spifns_stream_set_debug_callback(long ptr ptr)
@ cdecl spifns_stream_unlock(long)
